### ISSUE TITLE
Cannot open the files

### ISSUE THREAD

**Issue by ChamathAkalankancbc** [suryaya/tuflow_ensemble#17]
Hi,

I have renamed my csv files as Figure 1.

![1](https://github.com/hydroEng/StormViewer/assets/152950706/09066718-b195-42e8-a222-16c293ca3143)

I tried to open SV and select this folder and the program says it could not read the results. (Figure 2)

![2](https://github.com/hydroEng/StormViewer/assets/152950706/83714a55-38c4-49f8-920b-90b7dd8bfe99)

A sample of data inside a csv is demonstrated in Figure 3
![3](https://github.com/hydroEng/StormViewer/assets/152950706/ed0bd75b-9c53-4f5f-8565-32972fa98b7a)
 
Could you please assist me to solve this matter?
Much Appreciated

Thank you

**Comment by hydroEng** [comment]
Hi Chamath, 

What version of TUFLOW are you using? Your data seems generated slightly different to the versions I have tested on. For reference, this is the data (note the column names):

![image](https://github.com/hydroEng/StormViewer/assets/59785388/9c78955b-4640-40c4-bffe-0acb950834d6)

**Comment by ChamathAkalankancbc** [comment]
Thank so much! I use TUFLOWEXE=C:\temp\TUFLOW\2023-03-AC\TUFLOW_iSP_w64.exe

But appreciate your efforts on replying to me. I will try the format provided

**Comment by hydroEng** [comment]
Thanks. The 2023 version should work, I guess the data output looks a little bit different. Could I ask how this data was generated? Was it just the resulting files from the PO lines in your model?

**Comment by ChamathAkalankancbc** [comment]
Hi Could you please check the below. 
This for a 1%AEP evnt = 0.01EY event for 24 hours

my folder 
![4](https://github.com/hydroEng/StormViewer/assets/152950706/8f43b038-481b-4f02-a8dc-38bc47e85f49)

Data inside
![5](https://github.com/hydroEng/StormViewer/assets/152950706/82a71d84-6cb2-4294-8702-605d71182ca5)

Could you please tell what error i am doing, please?
I am sure I am doing something wrong

**Comment by hydroEng** [comment]
Can you please send me the data as a zip?

**Comment by ChamathAkalankancbc** [comment]
[Yoorndoo_0.01EY_1440m_TP01_PO.csv](https://github.com/hydroEng/StormViewer/files/14477627/Yoorndoo_0.01EY_1440m_TP01_PO.csv)
[Yoorndoo_0.01EY_1440m_TP02_PO.csv](https://github.com/hydroEng/StormViewer/files/14477628/Yoorndoo_0.01EY_1440m_TP02_PO.csv)
[Yoorndoo_0.01EY_1440m_TP03_PO.csv](https://github.com/hydroEng/StormViewer/files/14477629/Yoorndoo_0.01EY_1440m_TP03_PO.csv)
[Yoorndoo_0.01EY_1440m_TP04_PO.csv](https://github.com/hydroEng/StormViewer/files/14477630/Yoorndoo_0.01EY_1440m_TP04_PO.csv)

[Yoorndoo_0.01EY_1440m_TP05_PO.csv](https://github.com/hydroEng/StormViewer/files/14477631/Yoorndoo_0.01EY_1440m_TP05_PO.csv)

[Yoorndoo_0.01EY_1440m_TP06_PO.csv](https://github.com/hydroEng/StormViewer/files/14477632/Yoorndoo_0.01EY_1440m_TP06_PO.csv)
[Yoorndoo_0.01EY_1440m_TP07_PO.csv](https://github.com/hydroEng/StormViewer/files/14477633/Yoorndoo_0.01EY_1440m_TP07_PO.csv)
[Yoorndoo_0.01EY_1440m_TP08_PO.csv](https://github.com/hydroEng/StormViewer/files/14477634/Yoorndoo_0.01EY_1440m_TP08_PO.csv)
[Yoorndoo_0.01EY_1440m_TP09_PO.csv](https://github.com/hydroEng/StormViewer/files/14477635/Yoorndoo_0.01EY_1440m_TP09_PO.csv)
[Yoorndoo_0.01EY_1440m_TP10_PO.csv](https://github.com/hydroEng/StormViewer/files/14477636/Yoorndoo_0.01EY_1440m_TP10_PO.csv)


I tried to upload a zip but failed. Hence I am sending the 10 excels, if you dont mind
Much appreciated thank you

**Comment by hydroEng** [comment]
Thanks, I'll have a look (hopefully soon).

**Comment by ChamathAkalankancbc** [comment]
No Stress. Appreciate it

**Comment by hydroEng** [comment]
Ok, so it seems to work for me when running the python file directly (gui.py). I will log into a windows machine and try the .exe. if the data is fine, it might be a file permissions thing. 


![image](https://github.com/hydroEng/StormViewer/assets/59785388/fc40a6b3-e2ff-40cb-81dd-a591cc7fd97b)

**Comment by ChamathAkalankancbc** [comment]
Thank you so much. Let me know the results please. Much appreciated

**Comment by hydroEng** [comment]
Ok, it doesn't seem to be a software issue as its definitely working on my machine. Can you try run as administrator?

I can provide the results for you but I am not sure if theres any utility in analysing just one duration. 

![image](https://github.com/hydroEng/StormViewer/assets/59785388/64564e04-1c1f-44a0-9fd6-9620ed60f210)

**Comment by ChamathAkalankancbc** [comment]
Thank you sir! I will try from my end now. Now at least I know there is nothing wrong with my naming of files

Thanks a lot and much appreciated for your time

**Comment by hydroEng** [comment]
No worries, thanks for opening the issue.

**Comment by ChamathAkalankancbc** [comment]
![7](https://github.com/hydroEng/StormViewer/assets/152950706/d99226fc-a1c0-4424-a8ff-638da09567bd)


Finally, it worked!! Thank you so much!
As you said I run as the adminstrator

![8](https://github.com/hydroEng/StormViewer/assets/152950706/db4da09d-0cac-4488-a1ae-4a5c03a53d2f)
